### ISSUE TITLE
[BUG]: In documentation dataDoNoTrack should be dataDotNotTrack

### ISSUE THREAD

**Issue by vporoshin** [dipakparmar/docusaurus-plugin-umami#22]
### Description of the bug

In README dataDoNoTrack should be dataDotNotTrack

### Steps To Reproduce

Error while running : `ValidationError: "dataDoNoTrack" is not allowed`

**Comment by dipakparmar** [comment]
Thanks @vporoshin for reporting this! Yes, that's a typo in readme docs, however, the type naming is correct. 

Fixed in #23
