### ISSUE TITLE
Set isProd variable as a parameter of the plugin

### ISSUE THREAD

**Issue by miquelmongeAZ** [dipakparmar/docusaurus-plugin-umami#55]
### Description

In /src it is specify the env to be "production", which have sense:
```bash
const isProd = process.env.NODE_ENV === "production";
```

But the nomenclature for this can vary in different projects, it can be "prd", "prod" or some other variations.
To avoid this, I guess it is a good idea to pass this variable as a new entry of the plugin:

```bash
module.exports = {
  plugins: [
    [
      "@dipakparmar/docusaurus-plugin-umami",
      /** @type {import('@dipakparmar/docusaurus-plugin-umami').Options} */
      ({
        websiteID: "your-website-id", // Required
        / etc
        env: "your prod env name (prd, prod, production, etc)
      }),
    ],
  ],
};
```
And maybe keep the default value to "production" as it is now.

This will also be helpful to help test the integration in "dev" environment before pushing the code into de "prod" directly.

_No response_

**Comment by miquelmongeAZ** [comment]
@dipakparmar what do you think?

**Comment by dipakparmar** [comment]
Hey @miquelmongeAZ, for some reason, I have doubts about your request, and it feels like your account is automated. 

You can use a simple workaround as below:

```bash
export NODE_ENV=production npm run start
```

I know it's not ideal, but it will help you to test. In the future, when I have time, I may add a toggle option to enable/disable the plugin, replacing the current default behavior where it's disabled in a development environment.
